spring.datasource:
    url: jdbc:h2:./camunda-db
    username: sa
    password: sa

camunda.bpm.admin-user:
  id:       demo
  password: demo

spring.security.user:
  name:     demo
  password: demo
  